spring:
  application:
    name: mi-changarro-app

  datasource:
    url: jdbc:postgresql://localhost:5432/mi_changarro
    username: postgres
    password: 1925Bautista

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
